import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createServer } from 'vite';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import ts from 'typescript';

const origin = 'https://kolkata-bus.vercel.app';
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const slug = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const data = JSON.parse(await readFile('src/data/busdata.json', 'utf8'));
async function loadData(file) {
  const source = await readFile(file, 'utf8');
  const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
  return import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
}
const { metroLines, metroStations } = await loadData('src/data/metroData.ts');
const { trainLines, trainStations } = await loadData('src/data/trainData.ts');
const { ferryRoutes } = await loadData('src/data/ferryData.ts');
const unique = [...new Map(data.routes.map(route => [route.busNumber, route])).values()];
// Publish detailed, distinct route guides gradually; the planner still searches the whole dataset.
const routes = ['private', 'government'].flatMap(type => unique.filter(route => route.type === type && route.stops.length >= 3).slice(0, 80));
const routePaths = new Map(routes.map(route => [route.busNumber, `/bus-routes/${slug(route.busNumber)}/`]));
if (new Set(routePaths.values()).size !== routes.length) throw new Error('Route slug collision');
const stopCounts = new Map();
for (const route of routes) for (const stop of new Set(route.stops)) stopCounts.set(stop, (stopCounts.get(stop) ?? 0) + 1);
const stops = [...stopCounts].sort((a, b) => b[1] - a[1]).slice(0, 40).map(([name]) => name);
const stopPaths = new Map(stops.map(stop => [stop, `/stops/${slug(stop)}/`]));
const pages = new Map();
const nav = [['/', 'Journey planner'], ['/bus-routes/', 'Bus routes'], ['/stops/', 'Stops'], ['/metro/', 'Metro'], ['/trains/', 'Trains'], ['/ferries/', 'Ferries'], ['/guide/', 'Travel guide']];
const link = (path, label) => `<a href="${escape(path)}">${escape(label)}</a>`;
const list = items => `<ul class="cards">${items.map(item => `<li>${item}</li>`).join('')}</ul>`;
const notice = '<aside class="notice">Independent route guide based on the project dataset. Services, stop names and coordinates may be incomplete or outdated. Confirm current operation, direction, fare and timings with the operator before travel. This is not live transport information.</aside>';
const orderedStops = names => `<ol class="stops">${names.map(name => `<li>${stopPaths.has(name) ? link(stopPaths.get(name), name) : escape(name)}</li>`).join('')}</ol>`;
function add(path, title, description, body, options = {}) { pages.set(path, { title, description, body, ...options }); }
const routeCard = route => `${link(routePaths.get(route.busNumber), route.busNumber)}<small>${escape(route.stops[0])} → ${escape(route.stops.at(-1))} · ${route.stops.length} listed stops</small>`;
add('/bus-routes/', 'Kolkata Bus Route Directory', 'Browse Kolkata bus route guides with ordered stops and links to the interactive route finder.', `<p>Browse ${routes.length} detailed route guides. The ${link('/', 'interactive planner')} searches the wider dataset by bus number or two stops.</p>${notice}${list(routes.map(routeCard))}`);
for (const route of routes) {
  const related = routes.filter(other => other.busNumber !== route.busNumber && other.stops[0] === route.stops[0]).slice(0, 5);
  add(routePaths.get(route.busNumber), `${route.busNumber} Bus Route: ${route.stops[0]} to ${route.stops.at(-1)}`, `See ${route.busNumber} bus stops from ${route.stops[0]} to ${route.stops.at(-1)} in the Kolkata route dataset. Open the route on the map.`, `<p><strong>${escape(route.stops[0])} → ${escape(route.stops.at(-1))}</strong></p><p>Dataset category: ${escape(route.type)} bus. ${route.stops.length} listed stops.</p><p>${link(`/?bus=${encodeURIComponent(route.busNumber)}`, 'Open this bus in the interactive planner')}</p>${notice}<h2>Stops in dataset order</h2>${orderedStops(route.stops)}<h2>Planning this journey</h2><p>The planner shows the listed stops and a calculated road path where routing is available. A calculated path can differ from the actual bus alignment. Confirm the destination board and boarding side; this dataset does not verify that every listed service operates in both directions.</p><p>No verified timetable or fare is available for this route. Ask the operator or conductor for current details.</p>${related.length ? `<h2>Other routes from ${escape(route.stops[0])}</h2>${list(related.map(routeCard))}` : ''}`, { parent: '/bus-routes/' });
}
add('/stops/', 'Kolkata Bus Stops and Route Connections', 'Find Kolkata bus stops, listed route connections and links to plan your journey.', `<p>Explore ${stops.length} frequently shared stops in our published route guides. Search other stops in the ${link('/', 'planner')}.</p>${notice}${list(stops.map(stop => `${link(stopPaths.get(stop), stop)}<small>${stopCounts.get(stop)} published route guides</small>`))}`);
for (const stop of stops) {
  const served = routes.filter(route => route.stops.includes(stop));
  add(stopPaths.get(stop), `${stop} Bus Stop: Kolkata Route Connections`, `Browse ${served.length} published bus route guides listing ${stop}. Find stops and plan a Kolkata journey.`, `<p>${served.length} published bus route guides list ${escape(stop)}. This is a subset of the searchable dataset, not a live departure board.</p>${notice}<h2>Routes listing ${escape(stop)}</h2>${list(served.map(routeCard))}<h2>Boarding and transfers</h2><p>Search ${escape(stop)} as the origin in the ${link('/', 'journey planner')}. Check the bus destination board and local signage for the correct side of the road. Stops sharing a name can refer to different boarding points; transfer walking distances are not verified.</p>`, { parent: '/stops/' });
}
for (const [path, title, lines, stations, mode] of [['/metro/', 'Kolkata Metro Lines and Station Map', metroLines, metroStations, 'metro'], ['/trains/', 'Kolkata Local Train Network and Stations', trainLines, trainStations, 'train']]) {
  add(path, title, `Explore ${lines.length} dataset lines, station lists and full-network maps for ${mode === 'metro' ? 'Kolkata Metro' : 'Kolkata suburban trains'}.`, `<p>${link(`/?mode=${mode}`, 'Open the full network map')} to zoom, pan and explore station locations.</p>${notice}${mode === 'metro' ? '<p>The diagram includes planned corridors. A station appearing here does not confirm that it is open or served today.</p>' : '<p>These are selected corridors, not the complete Eastern Railway network. Station connectors and stored geometry are indicative and are not verified GPS tracks.</p>'}${lines.map(line => `<section><h2 style="border-left:5px solid ${escape(line.color)};padding-left:12px">${escape(line.name)}</h2><p>${line.stations.length} stations in the dataset corridor.</p>${orderedStops(line.stations.filter(id => stations[id]).map(id => stations[id].name))}</section>`).join('')}<p>Consult ${link(mode === 'metro' ? 'https://mtp.indianrailways.gov.in/' : 'https://er.indianrailways.gov.in/', mode === 'metro' ? 'Metro Railway Kolkata' : 'Eastern Railway')} for operating notices and schedules.</p>`);
}
add('/ferries/', 'Hooghly River Ferry Routes and Ghat Map', 'Explore Hooghly River ferry connections, ghats and the Kolkata ferry map. Confirm current fares and service at the ghat.', `<p>${link('/?mode=ferry', 'Open the ferry map')} for an overview of the river connections in our dataset.</p>${notice}<p>Lines join ghats schematically; they do not represent a measured vessel track. Fares and timings shown in the planner are unverified dataset estimates.</p>${ferryRoutes.map(route => `<section><h2>${escape(route.name)}</h2><p>${escape(route.from.name)} → ${escape(route.to.name)}</p><p>Confirm ticket price, last departure and accessibility at the ghat. Weather, tides and operator changes can affect service.</p></section>`).join('')}<p>Check ${link('https://wbtc.co.in/', 'West Bengal Transport Corporation')} notices before travel.</p>`);
add('/guide/', 'How to Plan a Kolkata Bus, Metro, Train or Ferry Journey', 'Use stop search, bus numbers, saved journeys and transport maps to plan travel around Kolkata.', `<p>${link('/bn/guide/', 'বাংলায় পড়ুন')} · ${link('/', 'Open the planner')}</p><h2>Find a journey between stops</h2><ol><li>Choose Plan Journey, type the starting stop, and select a suggestion.</li><li>Select the destination, then choose Find. You can swap the two stops.</li><li>Expand a direct route or a connection to inspect the stop sequence. Show on map centers the selected route.</li><li>Check the operator, boarding direction and current service before travelling.</li></ol><h2>Find a specific bus</h2><p>Use Find Bus and select the complete bus name from suggestions. Variants with different destinations may share a number. The route guide lists the dataset stop order, not live arrivals.</p><h2>Explore the networks</h2><p>Metro and Trains open with the complete schematic fitted to the screen. Zoom to read names, drag to pan, or use Fit full network to reset. Actual Map displays geographic locations. Ferry opens directly on its map; select a connection to focus it.</p><h2>Save, share and use location</h2><p>Star a journey to save it in this browser. Shared links restore the search when opened. If sharing is unavailable, use the copyable link. Nearby Stops requests browser location permission and searches the local dataset within 2 km; you can always type a stop instead.</p><h2>Understanding map paths</h2><p>Solid calculated bus paths follow roads through known stop coordinates. Dashed links mean exact geometry is unavailable. Metro, train and ferry paths are indicative; maps do not confirm operating service.</p>${notice}`, { alternate: '/bn/guide/' });
add('/bn/guide/', 'কলকাতার বাস, মেট্রো, ট্রেন ও ফেরি যাত্রার নির্দেশিকা', 'স্টপের নাম, বাস নম্বর, সংরক্ষিত যাত্রা এবং মানচিত্র ব্যবহার করে কলকাতায় যাতায়াতের পরিকল্পনা করুন।', `<p>${link('/guide/', 'Read in English')} · ${link('/', 'রুট প্ল্যানার খুলুন')}</p><h2>দুটি স্টপের মধ্যে যাত্রা খুঁজুন</h2><ol><li>Plan Journey বেছে শুরুর স্টপের নাম লিখুন এবং তালিকা থেকে নির্বাচন করুন।</li><li>গন্তব্য নির্বাচন করে Find চাপুন। তীর বোতাম দিয়ে শুরুর ও শেষের স্টপ বদলাতে পারবেন।</li><li>রুট খুলে স্টপের তালিকা ও বাস বদলানোর স্থান দেখুন। Show on map দিয়ে মানচিত্রে দেখুন।</li></ol><h2>বাস নম্বর ও মানচিত্র</h2><p>Find Bus-এ সম্পূর্ণ বাসের নাম নির্বাচন করুন। একই নম্বরের বিভিন্ন গন্তব্য থাকতে পারে। Metro এবং Trains-এ প্রথমেই পুরো নেটওয়ার্ক দেখা যায়। নাম পড়তে জুম করুন। Ferry-তে মানচিত্র খুলে সংযোগ নির্বাচন করুন।</p><h2>যাত্রা সংরক্ষণ ও শেয়ার</h2><p>তারকা বোতামে যাত্রা এই ব্রাউজারে সংরক্ষিত হবে। শেয়ার করা লিঙ্ক খুললে অনুসন্ধান ফিরে আসবে। Nearby Stops ব্যবহার করতে অবস্থানের অনুমতি লাগবে; চাইলে স্টপের নাম নিজেই লিখতে পারেন।</p><h2>ভ্রমণের আগে যাচাই করুন</h2><p>এই স্বাধীন প্ল্যানার প্রকল্পের ডেটা ব্যবহার করে। এটি লাইভ সময়সূচি নয়। মেট্রোর পরিকল্পিত অংশও মানচিত্রে থাকতে পারে। রাস্তার গণনা করা পথ বাসের আসল পথের থেকে আলাদা হতে পারে। বাসের দিক, বর্তমান পরিষেবা, ভাড়া ও সময় অপারেটরের কাছে যাচাই করুন।</p>`, { lang: 'bn', alternate: '/guide/' });
add('/about/', 'About Kolkata Travel Router and Its Data', 'Understand the data sources, map providers and limitations of the independent Kolkata journey planner.', `<p>Kolkata Travel Router is a free, independent project for exploring public transport routes. It is not an official service of WBTC, Kolkata Metro, Eastern Railway or WBSTC.</p><h2>Data and limitations</h2><p>Route sequences, stations and ghats come from JSON and TypeScript datasets maintained in the ${link('https://github.com/RITESHKUMAR7488/Kolkata_Bus', 'public project repository')}. The repository does not establish a verified update date or current operational status for every service. Coordinates can be missing or approximate. No live vehicle positions, ticket booking or verified timetable feed is provided.</p><h2>Maps</h2><p>Basemap tiles use ${link('https://www.openstreetmap.org/copyright', 'OpenStreetMap contributors')} with visible attribution. Road routing uses an external OSRM-compatible service through known stops. Routes are calculated for roads and can differ from bus alignments. Railway and ferry drawings are indicative.</p><h2>Official travel information</h2>${list([link('https://wbtc.co.in/', 'West Bengal Transport Corporation'), link('https://mtp.indianrailways.gov.in/', 'Metro Railway Kolkata'), link('https://er.indianrailways.gov.in/', 'Eastern Railway')])}<p>${link('/contact/', 'Report incorrect data')} · ${link('/privacy/', 'Privacy and browser storage')}</p>`);
add('/contact/', 'Report a Kolkata Route or Map Correction', 'Report incorrect stops, routes or map locations to the Kolkata Travel Router project.', `<p>Found an incorrect stop, route or map position? ${link('https://github.com/RITESHKUMAR7488/Kolkata_Bus/issues', 'Open the project issue tracker')} to review reports or submit a correction using your GitHub account.</p><h2>Helpful correction details</h2><ul><li>Bus number or transport line and the affected stop.</li><li>What the planner currently shows and the corrected public information.</li><li>A reliable public source and the date you checked it.</li></ul><p>Do not include private location history, contact details or other personal information in a public report. This project cannot provide operator customer support or guarantee a reply time.</p><p>${link('/about/', 'Read about the data')} · ${link('/', 'Return to planner')}</p>`);
add('/privacy/', 'Privacy and Browser Storage', 'How Kolkata Travel Router uses saved journeys, optional location, map services and analytics.', '<h2>Saved journeys and preferences</h2><p>Favourites and the theme preference are saved in this browser’s local storage. Remove saved journeys using their remove button, or clear site data in browser settings. No account is required.</p><h2>Optional location</h2><p>Nearby Stops calculates distances on your device. Location is requested only when you press the location button. Centering a map loads tiles for that area from the map provider. You can decline permission and search manually.</p><h2>External services</h2><p>OpenStreetMap tiles and the road routing service receive the map requests needed to draw routes. Road requests contain public stop coordinates. The site also loads Google Fonts and uses Google Analytics for usage measurement. These providers receive network information such as IP address under their own policies.</p><h2>Sharing</h2><p>Shared URLs contain the selected stop names or bus number. Share only journeys you are comfortable revealing. This site has no payment or ticket booking service.</p>');

const css = `:root{font-family:Inter,system-ui,sans-serif;color:#1c2431;background:#f4f6f9;line-height:1.65}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:1120px;margin:auto;padding:24px}header{border-bottom:1px solid #dfe3e8}nav{display:flex;flex-wrap:wrap;gap:10px 18px}a{color:#a83a13;text-underline-offset:3px;overflow-wrap:anywhere}a:focus-visible{outline:3px solid #ff6b35;outline-offset:4px}h1{font-size:clamp(1.65rem,4vw,2.6rem);line-height:1.22;overflow-wrap:anywhere}h2{margin-top:32px;line-height:1.35}.brand{font-weight:750;font-size:22px;color:#18202e;text-decoration:none;display:block;margin-bottom:14px}.notice{background:#fff2e8;border:1px solid #f3c9af;border-radius:12px;padding:16px;margin:20px 0;font-size:14px}.cards{list-style:none;padding:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:12px}.cards li,section{background:white;border:1px solid #e2e6ed;border-radius:14px;padding:18px}.cards a{font-weight:650}small{display:block;color:#536071;margin-top:6px}.stops{padding-left:32px;columns:2;column-gap:32px}.stops li{padding:4px 0;break-inside:avoid}footer{border-top:1px solid #dfe3e8;font-size:13px}.crumbs{font-size:13px;margin-bottom:22px}.cta{display:inline-block;background:#ff6b35;color:white;padding:12px 18px;border-radius:10px;text-decoration:none;font-weight:650}@media(max-width:540px){header,main,footer{padding:18px}.stops{columns:1}}@media(prefers-color-scheme:dark){:root{color:#e9ecf1;background:#111118}.brand{color:#fff}a{color:#ffac8b}.cards li,section{background:#1c1c28;border-color:#383849}.notice{background:#2e211a;border-color:#60432e}small{color:#b6bdc9}}`;
function html(path, page) {
  const url = origin + path;
  const crumbs = [{ '@type': 'ListItem', position: 1, name: 'Journey planner', item: origin + '/' }];
  if (page.parent) crumbs.push({ '@type': 'ListItem', position: 2, name: pages.get(page.parent).title, item: origin + page.parent });
  crumbs.push({ '@type': 'ListItem', position: crumbs.length + 1, name: page.title, item: url });
  const schema = [{ '@context': 'https://schema.org', '@type': 'WebPage', name: page.title, description: page.description, url, inLanguage: page.lang === 'bn' ? 'bn-IN' : 'en-IN', isPartOf: { '@type': 'WebSite', name: 'Kolkata Travel Router', url: origin + '/' } }, { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: crumbs }];
  const alternate = page.alternate ? `<link rel="alternate" hreflang="en-IN" href="${origin}${page.lang === 'bn' ? page.alternate : path}"><link rel="alternate" hreflang="bn-IN" href="${origin}${page.lang === 'bn' ? path : page.alternate}"><link rel="alternate" hreflang="x-default" href="${origin}/guide/">` : '';
  return `<!doctype html><html lang="${page.lang ?? 'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)} | Kolkata Travel Router</title><meta name="description" content="${escape(page.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${url}">${alternate}<link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/og-image.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(page.title)}"><meta name="twitter:description" content="${escape(page.description)}"><meta name="twitter:image" content="${origin}/og-image.png"><style>${css}</style><script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script></head><body><header>${link('/', 'Kolkata Travel Router').replace('<a ', '<a class="brand" ')}<nav aria-label="Transport guides">${nav.map(([p, label]) => link(p, label)).join('')}</nav></header><main><nav class="crumbs" aria-label="Breadcrumb">${link('/', 'Journey planner')}${page.parent ? ' / ' + link(page.parent, pages.get(page.parent).title) : ''} / <span>${escape(page.title)}</span></nav><h1>${escape(page.title)}</h1>${page.body}<p><a class="cta" href="/">Plan another journey</a></p></main><footer><nav>${[['/about/', 'About and data'], ['/contact/', 'Corrections'], ['/privacy/', 'Privacy'], ['/guide/', 'English guide'], ['/bn/guide/', 'বাংলা নির্দেশিকা']].map(([p, label]) => link(p, label)).join('')}</nav><p>Independent project · Dataset information · Verify service before travel.</p></footer></body></html>`;
}
for (const [path, page] of pages) {
  const dir = `dist${path}`;
  await mkdir(dir, { recursive: true });
  await writeFile(`${dir}index.html`, html(path, page));
}
// Put meaningful visible content and real links in the homepage response before JavaScript loads.
const server = await createServer({ server: { middlewareMode: true }, appType: 'custom' });
try {
  const { default: SEOContent } = await server.ssrLoadModule('/src/components/SEOContent.tsx');
  const { default: ExploreLinks } = await server.ssrLoadModule('/src/components/ExploreLinks.tsx');
  const content = renderToStaticMarkup(createElement('div', { className: 'max-w-6xl mx-auto p-6' }, createElement('h1', null, 'Kolkata Bus Routes and Journey Planner'), createElement('p', null, 'Find bus routes between stops, explore metro and local train networks, and view Hooghly River ferry connections.'), createElement(ExploreLinks), createElement(SEOContent)));
  const home = await readFile('dist/index.html', 'utf8');
  await writeFile('dist/index.html', home.replace('<div id="root"></div>', `<div id="root">${content}</div>`));
} finally { await server.close(); }
const allPaths = ['/', ...pages.keys()];
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${allPaths.map(path => `<url><loc>${origin}${path}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/seo-manifest.json', JSON.stringify(allPaths, null, 2));
await writeFile('dist/404.html', '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Page not found | Kolkata Travel Router</title></head><body><h1>Page not found</h1><p><a href="/">Return to the Kolkata journey planner</a></p></body></html>');
console.log(`Generated ${allPaths.length} crawlable pages: ${routes.length} bus guides, ${stops.length} stop guides, transport and information pages.`);
